name: Update TCMB FX

on:
  schedule:
    - cron: "0 5 * * *"  # 08:00 Europe/Istanbul
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lme_automation
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci || npm i
      - run: npm run update:tcmb
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto-update tcmb.json"
          file_pattern: "lme_automation/tcmb.json lme_automation/package-lock.json"
          add_options: "-A"
