name: Update metals.json (Metals.Dev → lme_automation)

on:
  schedule:
    - cron: "0 5 * * *"   # daily 08:00 Türkiye
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build lme_automation/lme.json (new automation only)
        env:
          METALS_DEV_API_KEY: ${{ secrets.METALS_DEV_API_KEY }}
          OUT_PATH: lme_automation/lme.json
        run: |
          mkdir -p "$(dirname "$OUT_PATH")"
          node - <<'NODE'
          const fs = require('fs');
          const path = process.env.OUT_PATH || 'lme_automation/lme.json';
          const key  = process.env.METALS_DEV_API_KEY;
          if (!key) throw new Error('Missing METALS_DEV_API_KEY');

          const url = `https://api.metals.dev/v1/latest?api_key=${key}&currency=USD&unit=kg`;

          (async () => {
            const r = await fetch(url, { headers: { Accept: 'application/json' }});
            const d = await r.json();
            if (d.status !== 'success') { console.error(d); process.exit(1); }

            const m = d.metals || {};
            const c = d.currencies || {};
            const usdtry = c.TRY ? (1 / c.TRY) : null;

            const out = {
              timestamp: d.timestamp ?? new Date().toISOString(),
              currency: 'USD',
              unit: 'kg',
              source: 'metals.dev/latest',
              usd_per_kg: {
                aluminum: m.lme_aluminum ?? m.aluminum ?? null,
                copper:   m.lme_copper   ?? m.copper   ?? null,
                lead:     m.lme_lead     ?? m.lead     ?? null,
                nickel:   m.lme_nickel   ?? m.nickel   ?? null,
                zinc:     m.lme_zinc     ?? m.zinc     ?? null
              },
              usdtry
            };

            fs.writeFileSync(path, JSON.stringify(out, null, 2));
            console.log('Wrote', path);
            console.log('Preview:', { copper_usd_per_kg: out.usd_per_kg.copper, usdtry: out.usdtry });
          })().catch(e => { console.error(e); process.exit(1); });
          NODE

      - name: Commit & push ONLY lme_automation/lme.json
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f lme_automation/lme.json
          git commit -m "chore: update lme_automation/lme.json (Metals.Dev)" || { echo "No changes"; exit 0; }
          git push
